### ISSUE TITLE
Before continuing with apartment type, do first proper user registration

### ISSUE THREAD

**Issue by dmpe** [dmpe/django-wohn#3]
- [x] logout
  - proper logout redirect -> https://stackoverflow.com/a/31779289
  - Fixed in https://github.com/dmpe/django-wohn/commit/807e5c0686364f332e91842b0f1e509e68d8e628
  - was working only with function based views

- [x] registration (the same principle)
  - cannot properly test login before registration is not done
  - <https://stackoverflow.com/a/50330016>

- [x] a simple login via username & email (!)
  - [x] class based approaches necessary, e.g. <https://stackoverflow.com/a/34035722>, <https://docs.djangoproject.com/en/2.1/topics/class-based-views/intro/#using-class-based-views>
    -  works as of https://github.com/dmpe/django-wohn/commit/f300f7a9bcf0270eb9d81c83f34ce00cb98fea36
    - works again as of https://github.com/dmpe/django-wohn/commit/a4e3e783ba3ca38022ad1916fd4d300d8892f7ad
  - [x] login via username
  - [x] login via email 

- [x] password reset
  - [x] token generation and URL
     - [x] Username is working as of https://github.com/dmpe/django-wohn/commit/128a1f26715ac8da05f042eb473dcdae21e91f72
     - [x] Token with URL generated <https://www.programcreek.com/python/example/88555/django.contrib.auth.tokens.PasswordResetTokenGenerator>, <https://stackoverflow.com/a/47178385>
       - working as of <https://github.com/dmpe/django-wohn/commit/947de9d841303eb1048a63e37652cd5554cd1a13>
       - [x] checking implemented
          - working as of <https://github.com/dmpe/django-wohn/commit/df48f316a01c7f480041cd86690a764b2c2a5538>, <https://github.com/dmpe/django-wohn/commit/676a4bdf3d4cb41502c0e2adf6861b139841c67e>, <https://github.com/dmpe/django-wohn/commit/9146f67f53eb66653a228d57e5172e0b3d4e214f>
  - [x] sending "password email"
     - working as of https://github.com/dmpe/django-wohn/commit/9334bf7db12c7960fe540a158c30e98672f81e49
   - <https://www.troyhunt.com/everything-you-ever-wanted-to-know/>
   - <https://stackoverflow.com/a/49894619>

- [x] only then with social things
  - Seems to work

Always whole workflow
